nodes:
  notizie:
    type: post_type
    post_type: post,
    posts_per_page: -1
    post_parent: 0,
    order: DESC
    changefreq: weekly
    priority: 0.6
  pagine:
    type: post_type
    post_type: page
    multilang: true
    changefreq: daily
    priority: 1
  tag:
    type: tax
    taxonomy: post_tag
    hide_empty: false
    changefreq: monthly
    priority: 0.8